### PR TITLE
Distribute compiled js instead of coffee

### PR DESCRIPTION
**Pull request by tatethurston**
This allows anyone to consume the project without compiling the
coffeescript themselves.

### CODE REVIEW

**Comment by scottyantipa** [comment]
Please add `/dist` to .gitignore.

**Comment by scottyantipa** [comment]
@tatethurston The final dist/index.js includes all dependencies, including vendor libs like React.

**Comment by tatethurston** [comment]
@scottyantipa We can't ignore /dist until you distribute this via npm instead of github

**Comment by tatethurston** [comment]
I stopped bundling, this requires that we drop extensions from imports. The coffeescript compiler does not change import paths.

**Pull request merged**
